component_depth: 1
languages:
- java
exclude:
- ./apache-maven/.*
- ./bin/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/maven/.*
- ./bin/org/apache/maven/artifact/.*
- ./bin/org/apache/maven/artifact/deployer/.*
- ./bin/org/apache/maven/artifact/factory/.*
- ./bin/org/apache/maven/artifact/handler/.*
- ./bin/org/apache/maven/artifact/handler/manager/.*
- ./bin/org/apache/maven/artifact/installer/.*
- ./bin/org/apache/maven/artifact/manager/.*
- ./bin/org/apache/maven/artifact/metadata/.*
- ./bin/org/apache/maven/artifact/repository/.*
- ./bin/org/apache/maven/artifact/repository/layout/.*
- ./bin/org/apache/maven/artifact/repository/metadata/.*
- ./bin/org/apache/maven/artifact/repository/metadata/io/.*
- ./bin/org/apache/maven/artifact/resolver/.*
- ./bin/org/apache/maven/artifact/resolver/filter/.*
- ./bin/org/apache/maven/artifact/versioning/.*
- ./bin/org/apache/maven/classrealm/.*
- ./bin/org/apache/maven/cli/.*
- ./bin/org/apache/maven/configuration/.*
- ./bin/org/apache/maven/configuration/internal/.*
- ./bin/org/apache/maven/embedder/.*
- ./bin/org/apache/maven/eventspy/.*
- ./bin/org/apache/maven/eventspy/internal/.*
- ./bin/org/apache/maven/exception/.*
- ./bin/org/apache/maven/execution/.*
- ./bin/org/apache/maven/lifecycle/.*
- ./bin/org/apache/maven/lifecycle/internal/.*
- ./bin/org/apache/maven/lifecycle/internal/stub/.*
- ./bin/org/apache/maven/lifecycle/mapping/.*
- ./bin/org/apache/maven/lifecycle/test/.*
- ./bin/org/apache/maven/model/.*
- ./bin/org/apache/maven/model/building/.*
- ./bin/org/apache/maven/model/composition/.*
- ./bin/org/apache/maven/model/inheritance/.*
- ./bin/org/apache/maven/model/interpolation/.*
- ./bin/org/apache/maven/model/io/.*
- ./bin/org/apache/maven/model/io/xpp3/.*
- ./bin/org/apache/maven/model/locator/.*
- ./bin/org/apache/maven/model/management/.*
- ./bin/org/apache/maven/model/merge/.*
- ./bin/org/apache/maven/model/normalization/.*
- ./bin/org/apache/maven/model/path/.*
- ./bin/org/apache/maven/model/plugin/.*
- ./bin/org/apache/maven/model/profile/.*
- ./bin/org/apache/maven/model/profile/activation/.*
- ./bin/org/apache/maven/model/resolution/.*
- ./bin/org/apache/maven/model/superpom/.*
- ./bin/org/apache/maven/model/validation/.*
- ./bin/org/apache/maven/monitor/.*
- ./bin/org/apache/maven/monitor/event/.*
- ./bin/org/apache/maven/monitor/logging/.*
- ./bin/org/apache/maven/plugin/.*
- ./bin/org/apache/maven/plugin/descriptor/.*
- ./bin/org/apache/maven/plugin/internal/.*
- ./bin/org/apache/maven/plugin/lifecycle/.*
- ./bin/org/apache/maven/plugin/logging/.*
- ./bin/org/apache/maven/plugin/prefix/.*
- ./bin/org/apache/maven/plugin/prefix/internal/.*
- ./bin/org/apache/maven/plugin/version/.*
- ./bin/org/apache/maven/plugin/version/internal/.*
- ./bin/org/apache/maven/profiles/.*
- ./bin/org/apache/maven/profiles/activation/.*
- ./bin/org/apache/maven/project/.*
- ./bin/org/apache/maven/project/artifact/.*
- ./bin/org/apache/maven/project/canonical/.*
- ./bin/org/apache/maven/project/harness/.*
- ./bin/org/apache/maven/project/inheritance/.*
- ./bin/org/apache/maven/project/interpolation/.*
- ./bin/org/apache/maven/project/path/.*
- ./bin/org/apache/maven/project/validation/.*
- ./bin/org/apache/maven/properties/.*
- ./bin/org/apache/maven/properties/internal/.*
- ./bin/org/apache/maven/reporting/.*
- ./bin/org/apache/maven/repository/.*
- ./bin/org/apache/maven/repository/internal/.*
- ./bin/org/apache/maven/repository/legacy/.*
- ./bin/org/apache/maven/repository/legacy/metadata/.*
- ./bin/org/apache/maven/repository/legacy/repository/.*
- ./bin/org/apache/maven/repository/legacy/resolver/.*
- ./bin/org/apache/maven/repository/legacy/resolver/conflict/.*
- ./bin/org/apache/maven/repository/legacy/resolver/transform/.*
- ./bin/org/apache/maven/repository/metadata/.*
- ./bin/org/apache/maven/rtinfo/.*
- ./bin/org/apache/maven/rtinfo/internal/.*
- ./bin/org/apache/maven/settings/.*
- ./bin/org/apache/maven/settings/building/.*
- ./bin/org/apache/maven/settings/crypto/.*
- ./bin/org/apache/maven/settings/io/.*
- ./bin/org/apache/maven/settings/merge/.*
- ./bin/org/apache/maven/settings/validation/.*
- ./bin/org/apache/maven/toolchain/.*
- ./bin/org/apache/maven/toolchain/java/.*
- ./bin/org/apache/maven/usability/.*
- ./bin/org/apache/maven/usability/plugin/.*
- ./lib/.*
- ./maven-aether-provider/.*
- ./maven-artifact/.*
- ./maven-compat/.*
- ./maven-core/.*
- ./maven-embedder/.*
- ./maven-model/.*
- ./maven-model-builder/.*
- ./maven-plugin-api/.*
- ./maven-repository-metadata/.*
- ./maven-settings/.*
- ./maven-settings-builder/.*
